// <auto-generated/>
#pragma warning disable 1591
[assembly: global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute(typeof(CompiledRazorTemplates.Dynamic.RazorEngine_c22fc02da2bc43a59c178c91ca0b17c2), @"default", @"/Message.cshtml")]
namespace CompiledRazorTemplates.Dynamic
{
#line hidden
    using System.Threading.Tasks;
    using System;
    using System.Collections.Generic;
    using System.Linq;
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"37b4bd1123027269b8f1a4465f4542201821560b", @"/Message.cshtml")]
    internal class RazorEngine_c22fc02da2bc43a59c178c91ca0b17c2 : RazorEngine.Templating.TemplateBase<TimerTest.Message>
    {
#pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
            WriteLiteral("Hello ");
#nullable restore
#line 1 "Message.cshtml"
            Write(Model.Name);

#line default
#line hidden
#nullable disable
            WriteLiteral(", welcome to RazorEngine!");
        }
#pragma warning restore 1998
    }
}
#pragma warning restore 1591
